# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=200, verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
